### PR TITLE
Finished the msys2 buildscripts

### PR DESCRIPTION
**Pull request by MatschbirneLive**
Tested the script on a fresh msys2 install and no issues were found. To build you just simply need to run the build-mingw64.sh in the mingw64 shell.
Now native windows compilation should be possible :)

### CODE REVIEW

**Comment by RCJacH** [comment]
I'm on the verge of crying, tears of joy.
Thank you for the native windows buildscript!

**Comment by fundamental** [comment]
Thanks for the PR. Looking at the squashed sequence of commits there's only a few file additions in the end which is non-obvious with the individual commits. Would you prefer if you squashed the commit sequence or if I squashed it for you?

**Comment by MatschbirneLive** [comment]
Im still new to git so it probably would be better if you squash it for me.

**Comment by MatschbirneLive** [comment]
Seems like i found an issue: The binaries that should be in release mode are for some reason in demo mode. Im going to look into the issue.

**Comment by fundamental** [comment]
-DDemoMode and BUILD_MODE have slightly different flags. In your new scripts they're treated the same.

**Comment by MatschbirneLive** [comment]
Commits should be now squashed. Took me some time to find out.

**Comment by fundamental** [comment]
Awesome. The commit is now in the zynaddsubfx/zyn-fusion-build repo.

**Comment by MatschbirneLive** [comment]
Looks like it failed to build the libuv library, do you have any logs of the build process ?

**Comment by fluzz142857** [comment]
I found a workaround to this issue: paste the files into the correct directories while the script is running. I can go into more detail if you’d like.

**Pull request merged**
