### PR TITLE
added build scripts for rpi3 (GLES2) + new gl headers, added one more…

### PR DESCRIPTION
**Pull request by ctag-fh-kiel**
… sound bank file

### CODE REVIEW

**Comment by fundamental** [comment]
The script changes look fine, but why are you adding an instrument bank in the same commit?

Instrument banks are normally added to https://github.com/zynaddsubfx/instruments

**Comment by ctag-fh-kiel** [comment]
True, I just created an new merge request for the sound bank.
I will change the files in the build repo accordingly. However, I was also wondering if the updated gl headers should be rather commited in zest itself? including the changes in some of the other headers, what do you think? Btw. the Rpi3 is still pretty weak on CPU, demanding patches may quickly cause buffer underruns...

**Comment by fundamental** [comment]
Bump

**Comment by ctag-fh-kiel** [comment]
Re-writing commit...

**Pull request closed without merging**
