### PR TITLE
chown: mark -> $(whoami)

### PR DESCRIPTION
**Pull request by deadray6**
Self-explanatory, I guess.

### CODE REVIEW

**Comment by deadray6** [comment]
Also, I [forked the repository](https://github.com/deadray6/zyn-fusion-build) and wrote Linux (Ubuntu and probably other deb-based distros) build instructions (assumption made that this PR is merged)

I edited the README and added a wiki. I think that these instructions (maybe modified) should be in this repo.

**Comment by fundamental** [comment]
Thanks for the writeup for the docs. Those changes should merge just fine. Since they seem pretty reasonable I've added you as a collaborator for this repo which should let you merge the remaining commits. Let me know if you have any questions or if you prefer to use the PR mechanism rather than have direct access to this particular repo.

**Comment by deadray6** [comment]
Thank you! :blush:
I'll just repeat what I did on the work, because merging would be more difficult and I don't have a complete understanding of merging mechanism. :pensive:

**Comment by deadray6** [comment]
Oh, and I can't create the wiki page..

**Comment by deadray6** [comment]
Nevermind.

**Comment by deadray6** [comment]
I guess, finished!

**Pull request merged**
