### PR TITLE
Adds Dockerfile

### PR DESCRIPTION
**Pull request by MatheusRich**
Hey, I had some trouble setting up my env, so I decided to make a Dockerfile to help out!

You guys can test it running `./docker/build-docker.sh`.

Tell me if there's something more to do! :smile:

### CODE REVIEW

**Comment by fundamental** [comment]
Thanks for the PR. Right now the set of build scripts are getting a bit cluttered and I'm somewhat cautious about adding a docker script to them with a Makefile as I could see many users mistakenly looking at the build scripts and assuming docker was a hard dependency after seeing a folder mentioning it and a Makefile which is built to run it.

The latter might be a bias of my own, but generally when I see a make file I assume "that's the primary option" and overlook other scripts. As such it might make sense to have the docker files exist within a secondary folder to avoid this perception, or they could be on the repo's wiki.

Thoughts?

**Comment by MatheusRich** [comment]
@fundamental I got your point. I could rewrite this Makefile as a bash script. I could create a `docker` directory and move the current Makefile to it. What do you think?

**Comment by MatheusRich** [comment]
@fundamental Done! We should add this to the wiki tutorial, right?

**Comment by fundamental** [comment]
Thanks for the update. I'd add a mention of it to the tutorial, though for those not familiar with docker it might be good to list it as an alternative approach.

**Pull request merged**
